### PR TITLE
add README's Chinese version: README_CN.md

### PR DESCRIPTION
**Pull request by FrankKai**
update .gitignore: .idea to support ignore webstorm configfiles;
add README_CN.md

### CODE REVIEW

**Comment by Agontuk** [comment]
Can you update the readme with new changes from README.md ?

**Comment by FrankKai** [comment]
Of course, I can update the readme.
But in my opinion, add a Chinese version reference in README.md is better, just like this project: https://github.com/996icu/996.ICU

[中文版](README_CN.md's url)

In the future, vue-cropperjs can extend more different languages translation.

**Comment by Agontuk** [comment]
No I meant your PR is out of sync with the current README.md file I think :)

**Comment by FrankKai** [comment]
OK, I just made some changes in README_CN.md.

**Comment by FrankKai** [comment]
I just add a destroy() method revoke in beforeDestroy lifecycle to remove redundant DOM Nodes and listeners.

**Pull request closed without merging**
